spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: postgres
    password: password

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

management:
  endpoints:
    web:
      exposure:
        include: health, info

  endpoint:
    health:
      show-details: always

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: io.github.toku2001.reservation.mapper
